---
# Install Go

# Setup/install tasks.

- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Darwin.yml
  when: ansible_os_family == 'Darwin'