---
# Install Grafana Server

- name: Install Packages
  apt: 
    name:
      - uuid
    state: present
    autoclean: yes      
  become: yes
  become_user: root
  become_method: sudo

- name: Install Grafana deb package 
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_6.1.6_amd64.deb
  become: yes
  become_user: root
  become_method: sudo       

- name: Copy grafana.ini
  copy:
    src: files/grafana.ini
    dest: "/etc/grafana"
    owner: "grafana"
    group: "grafana"
    mode: 0640    
  become: yes
  become_user: root
  become_method: sudo
  notify: restart grafana

# - name: Copy ldap.toml
#   copy:
#     src: files/ldap.toml
#     dest: "/etc/grafana"
#     owner: "grafana"
#     group: "grafana"
#     mode: 0640    
#   become: yes
#   become_user: root
#   become_method: sudo
#   notify: restart grafana

- name: Enable and start grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes      
  become: yes
  become_user: root
  become_method: sudo

- name: Copy Grafana service definition
  copy:
    src: files/grafana.tpl
    dest: /etc/consul.d/grafana.tpl
    owner: consul
    group: consul
    mode: 0755
  become: yes
  become_user: root
  become_method: sudo
  when: setup_option == 'consul'

- name: Copy Grafana service definition
  copy:
    src: files/register.sh
    dest: /etc/consul.d/register.sh
    owner: consul
    group: consul
    mode: 0755
  become: yes
  become_user: root
  become_method: sudo
  when: setup_option == 'consul'

- name: Register Grafana with Consul
  shell: |
    set -e
    /etc/consul.d/register.sh
    exit 0    
  become: yes
  become_user: root
  become_method: sudo
  when: setup_option == 'consul'