---

# -------------------------------------------------------------------------------------
# Nomad
# -------------------------------------------------------------------------------------
- name: nomad
  hosts: "{{ target }}"
  user: "{{ user }}"
  become: yes
  become_user: root
  become_method: sudo  
  any_errors_fatal: true
  vars: 
    consul_version: "1.7.2"
    nomad_version: "1.0.0"
    consul_nodes: 
      - "tmt-vm1.7onetella.net"
      - "tmt-vm2.7onetella.net"
      - "tmt-vm3.7onetella.net"    
    nomad_nodes: 
      - "tmt-vm4.7onetella.net"
      - "tmt-vm5.7onetella.net"
      - "tmt-vm6.7onetella.net"
    docker_user: "nomad"
    docker_insecure_registry: "tmt-vm10.7onetella.net:5000"        
  roles:
    - role: consul-agent
    - role: nomad-agent
    - role: docker